/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface FavoriteProducts {
  id: Generated<number>;
  product_id: number;
  user_id: number;
}

export interface OrderProduct {
  id: Generated<number>;
  order_id: number;
  product_id: number;
  quantity: Generated<number>;
}

export interface Orders {
  city: string;
  confirmed: number;
  country: string;
  email: string;
  house_number: string;
  id: Generated<number>;
  name: string;
  phone_number: string;
  street: string;
  surname: string;
  user_id: number | null;
  zip_code: string;
}

export interface Products {
  category: string;
  description: string;
  id: Generated<number>;
  image: string;
  name: string;
  price: number;
}

export interface Session {
  expiration: number;
  id: Generated<number>;
  session_id: string;
  user_id: number;
}

export interface UserAddress {
  city: string;
  country: string;
  house_number: string;
  id: Generated<number | null>;
  name: string | null;
  phone_number: string | null;
  street: string;
  surname: string | null;
  user_id: number;
  zip_code: string;
}

export interface Users {
  email: string;
  id: Generated<number>;
  is_admin: Generated<number | null>;
  password: string;
  username: string;
}

export interface DB {
  favorite_products: FavoriteProducts;
  order_product: OrderProduct;
  orders: Orders;
  products: Products;
  session: Session;
  user_address: UserAddress;
  users: Users;
}
